name: Images Render

on:
  push:
    branches:
      - 'main'
    paths:
      - 'DeltaT32.kicad_pcb'

  workflow_dispatch:  # <--- Manual trigger button

jobs:
  render-images:
    name: PCB Render
    runs-on: ubuntu-latest

    steps:
      - name: Check Out the Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render PCB Images (PNG)
        uses: linalinn/kicad-render@main
        with:
          pcb_file: DeltaT32.kicad_pcb
          output_path: images

      - name: Render PCB GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: DeltaT32.kicad_pcb
          output_path: images
          animation: gif

      - name: Remove Old Rendered Images
        run: |
          rm -rf Images/*
          mkdir -p Images

      - name: Move New Images to Images/
        run: |
          cp -r images/* Images/

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Images/
          git commit -m "Update PCB render images for main" || echo "No changes to commit"
          git push origin main
