name: Images Render

on:
  push:
    branches:
      - 'main'
    paths:
      - 'DeltaT32.kicad_pcb'

jobs:
  render-images:
    name: PCB Render
    runs-on: ubuntu-latest

    steps:
      - name: Check Out the Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Render PCB Images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: DeltaT32.kicad_pcb
          output_path: images

      - name: Render PCB GIF
        uses: linalinn/kicad-render@main
        with:
          pcb_file: DeltaT32.kicad_pcb
          output_path: images
          animation: gif

      - name: Remove Old Images
        run: |
          rm -rf Images/* || true

      - name: Move New Images
        run: |
          mkdir -p Images
          mv images/* Images/

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Images/
          git commit -m "Update PCB images" || echo "No changes to commit"
          git push origin main
